Fix build error due to missing include.
queryresultprovider.h:45:18: error: 'function' in namespace 'std' does not name a template type
     typedef std::function<void(InputType, int)> ChangeHandler;

(Archlinux gcc 4.9.1)